# Generated by Django 2.1.5 on 2022-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="My Blog", max_length=250),
        ),
    ]
